### ISSUE TITLE
Add support for the table name

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-domain-language#2]
It was added in JHipster some time ago, just added in JHipster UML for UML editors.
Currently we can write:
```
entity A
```
A proposed syntax for the table name:
```
entityA(table_name)
```
Or even
```
entityA as table_name {
  ...
}
```

I'd rather have the first as it is the currently supported way of specifying a table for classes from XMI files.

If the user doesn't specify a table name, then the entity name will be used as table name (underscored first, then lowercased).

**Comment by deepu105** [comment]
ya first one is better

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
The implementation: if the user doesn't specify the table's name, then the entity's name will be used so as not to lose any information during the handling in any implementation (JHipster UML's, or any other). For instance, JHipster UML will always underscore the name, then lowercase everything. Any implementation is free to deal with it.

**Comment by deepu105** [comment]
Dont you think that would be redundant to handle again?  The entity sub
generator does the same since table name is optional if its not passed the
entity name is underscored and lowercased by default so even if you don't
pass a table it would work perfectly.

**Comment by MathieuAA** [comment]
If it's redundant, it's a "coincidence" (pardon the choice of the word, but it's kinda true).
There's a problem however: we can't handle it in here without some kind of layer between Peg and the real world because formatting the table's name would require either an external lib, or to do it ourselves.

I'm all for doing it in here, but we really have to discuss how we do it as we can't do it when the grammar is parsed (a limitation of the parser). Also, we need to deal with another business: the output format. We can't just parse the DSL and just return in after we change some of its data --especially now (I'll change some things with the parser next week). Do you have some kind of intermediary format that would be acceptable for JHipster (the generator + module/s)? Or can you think of one?
Whatever works for you Deepu.

**Comment by deepu105** [comment]
I dont get it, am i missing something? Why would you want to parse and
format it ?  Just pass the property as it is in the json and the entity sub
gen will take care of it. if its not passed as underscored the sub gen will
underscore it automatically

**Comment by MathieuAA** [comment]
So you want the table name to be nil instead to have the entity's name? Tell me if I don't understand what you're saying! it's pretty hard to know what the other is thinking when writing and not talking =/

**Comment by deepu105** [comment]
The table name parameter is an optional attribute for the entity sub
generator and hence if the user has not defined it do not set the attribute
in the json. That means do not define that key in json, entity sub gen will
add it automatically, take a look at the entity sub gen code.
