### ISSUE TITLE
Override default id name feature request

### ISSUE THREAD

**Issue by sam888** [jhipster/jhipster-domain-language#27]
Hi,

This is just a minor feature request. Currently, all the id will be generated
automatically, i.e.

entity Locale {}

This will generate a Locale table with Primary key '**id**' automatically. Can it be enhanced such that the name of this id field is customized by adding some syntax? E.g.

entity Locale {
    localeId Long id_override;
}

So in above example the keyword id_override will indicate the name of id will be localeId.

Thanks,
Sam

**Comment by deepu105** [comment]
I dont think we will do this as it would have other implications and is harder for us to maintain. If you want a different field for ID just add the field and ignore the generated ID its for internal use anyways.
