### ISSUE TITLE
service/dto/pagination options for entity not fully processed

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-domain-language#3]
This is a rather weird issue with parser in JHUML so it might or might not be present here as well

When there are say 4 instructions for serviceClass or serviceImpl only the last 2 are applied

eg:
```
service Region with serviceClass
service Task with serviceImpl

service Employee with serviceClass
service Department with serviceImpl
```

In the generated json files only Employee and Department had the option set, If I change the order again whichever entity comes last gets the option

**Comment by MathieuAA** [comment]
I've a fix for this (tests are being done), and I'm going to add it to JUML for now, and move all the code here when the migration's over.
