### ISSUE TITLE
relationships not generated

### ISSUE THREAD

**Issue by Blucky87** [jhipster/jhipster-domain-language#30]
The following does not fill in the relationship fields for any entities in the .json files that are generated. 

entity Organization {
	name String required,
    description String,
    createdDate ZonedDateTime,
    lastModifiedDate ZonedDateTime
}

entity Region {
	name String required,
    description String,
    createdDate ZonedDateTime,
    lastModifiedDate ZonedDateTime
}

entity Location {
	name String required,
    description String,
    latitude Float,
    longitude Float,
    altitude Float,
    createdDate ZonedDateTime,
    lastModifiedDate ZonedDateTime,
    markerIcon String
}

entity FormOutline {
	title String required,
    description String,
    createdDate ZonedDateTime,
    lastModifiedDate ZonedDateTime
}

entity FormComplete {
    createdDate ZonedDateTime,
    lastModifiedDate ZonedDateTime
}

entity FormOutlineString {
	label String required
}

entity FormOutlineFloat {
	label String required
}

entity FormOutlineDatetime {
	label String required
}

entity FormCompleteString {
	value String required
}

entity FormCompleteFloat {
	value Float required
}
entity FormCompleteDatetime {
	value ZonedDateTime required
}

relationship OneToMany {
	FormOutline{formoutlinestring(label)} to FormOutlineString{formoutline(title)},
    FormOutline{formoutlinefloat(label)} to FormOutlineFloat{formoutline(title)},
    FormOutline{formoutlinedatetime(label)} to FormOutlineDatetime{formoutline(title)},
    FormOutline{formcomplete} to FormComplete{formoutline(title)},
	FormComplete{formcompletestring(value)} to FormCompleteString{formcomplete},
    FormComplete{formcompletefloat(value)} to FormCompleteFloat{formcomplete},
    FormComplete{formcompletedatetime(value)} to FormCompleteDatetime{formcomplete},
    FormOutlineDatetime{formcompletedatetime} to FormCompleteDateTime{formoutlinedatetime(label)},
    FormOutlineString{formcompletestring} to FormCompleteString{formoutlinestring(label)},
    FormOutlineFloat{formcompletefloat} to FormCompleteFloat{formoutlinefloat(label)}
}

relationship ManyToMany {
    Region{location(name)} to Location{region(name)}
}

**Comment by deepu105** [comment]
How did you generate this? Using the import jdl sub or using jhipster uml?

Thanks & regards,
Deepu

**Comment by Blucky87** [comment]
I typed it into JDL studio on the jhipster site. it did not show any errors. so I put it in my project folder and typed the 'yo jhipster:import jdl ...' command to load it and it did nothing. I then tried loading each entity section on its own and it worked but the relationship section refused to load.

**Comment by deepu105** [comment]
The import jdl sub doesnt support multiple relationship definition in the
same block yet. Please use jhipster uml for this. We are working to make
the import jdl support all options. It should land soon

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Im gonna take some time off for this today and see if i can migrate to the newer JDL version. @jdubois need your help to rename the jdl project to jhipster-core as we decided earlier. Cc @MathieuAA

**Comment by MathieuAA** [comment]
The DSL parser to JDL objects is finished, the tests have yet to be updated.

Le 20 juin 2016 03:40:41 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>Im gonna take some time off for this today and see if i can migrate to
>the newer JDL version. @jdubois need your help to rename the jdl
>project to jhipster-core as we decided earlier. Cc @MathieuAA 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227034396

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
@MathieuAA Is it the one in the DSL parser branch? If so Im writing the entity creator for the generated JDL object now

**Comment by MathieuAA** [comment]
It is.

Le 20 juin 2016 09:04:59 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>@MathieuAA Is it the one in the DSL parser branch? If so Im writing the
>entity creator for the generated JDL object now
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227065008

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
Does your toStrings print the jhipster entity json format?


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Ok I guess your printing it in JDL syntax so I have to convert the parsed
data into the jhipster entity json format


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
No, in JDL.

Le 20 juin 2016 09:44:00 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>Does your toStrings print the jhipster entity json format?
>
>
>Thanks & Regards,
>Deepu
>
>On Mon, Jun 20, 2016 at 3:27 PM, Mathieu ABOU-AICHI <
>notifications@github.com> wrote:
>
>> It is.
>>
>> Le 20 juin 2016 09:04:59 GMT+02:00, Deepu K Sasidharan <
>> notifications@github.com> a écrit :
>> >@MathieuAA Is it the one in the DSL parser branch? If so Im writing
>the
>> >entity creator for the generated JDL object now
>> >
>> >---
>> >You are receiving this because you were mentioned.
>> >Reply to this email directly or view it on GitHub:
>> >
>>
>https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227065008
>>
>> --
>> Mathieu ABOU-AICHI
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>>
><https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227068554>,
>> or mute the thread
>>
><https://github.com/notifications/unsubscribe/ABDlF3Ogq5f2mdD88siYQH-PBhLZyK1Sks5qNkDOgaJpZM4I5Hkr>
>> .
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227071489

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
You can reuse some code from the entity creator for that... It's not too outdated

Le 20 juin 2016 09:47:08 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>Ok I guess your printing it in JDL syntax so I have to convert the
>parsed
>data into the jhipster entity json format
>
>
>Thanks & Regards,
>Deepu
>
>On Mon, Jun 20, 2016 at 3:43 PM, Deepu K Sasidharan <d4udts@gmail.com>
>wrote:
>
>> Does your toStrings print the jhipster entity json format?
>>
>>
>> Thanks & Regards,
>> Deepu
>>
>> On Mon, Jun 20, 2016 at 3:27 PM, Mathieu ABOU-AICHI <
>> notifications@github.com> wrote:
>>
>>> It is.
>>>
>>> Le 20 juin 2016 09:04:59 GMT+02:00, Deepu K Sasidharan <
>>> notifications@github.com> a écrit :
>>> >@MathieuAA Is it the one in the DSL parser branch? If so Im writing
>the
>>> >entity creator for the generated JDL object now
>>> >
>>> >---
>>> >You are receiving this because you were mentioned.
>>> >Reply to this email directly or view it on GitHub:
>>> >
>>>
>https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227065008
>>>
>>> --
>>> Mathieu ABOU-AICHI
>>>
>>> —
>>> You are receiving this because you modified the open/close state.
>>> Reply to this email directly, view it on GitHub
>>>
><https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227068554>,
>>> or mute the thread
>>>
><https://github.com/notifications/unsubscribe/ABDlF3Ogq5f2mdD88siYQH-PBhLZyK1Sks5qNkDOgaJpZM4I5Hkr>
>>> .
>>>
>>
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/30#issuecomment-227072013

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
ok will do that


Thanks & Regards,
Deepu
