### ISSUE TITLE
Replace "angularSuffixes" by "angularSuffix"

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-domain-language#31]
In the grammar, the pegjs parser must be built again.
[This](https://github.com/jhipster/jhipster-domain-language/blob/dslparser/lib/dsl/jdl_parser.js#L224) must be replaced as well, and [this](https://github.com/jhipster/jhipster-domain-language/blob/dslparser/lib/dsl/jdl_parser.js#L183) must only take two args because `name` = `key`.
cc @deepu105 (by the way, great work man!)

**Comment by deepu105** [comment]
Oh I didn't notice they are same. Ill replace those

**Comment by deepu105** [comment]
@MathieuAA check if this is ok. I have added an npm task to do the peg parsing as well. run `npm run peg-parse` to update the parser from grammer.txt

**Comment by MathieuAA** [comment]
Excellent. Thanks! 

Le 22 juin 2016 06:25:11 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>@MathieuAA check if this is ok. I have added an npm task to do the peg
>parsing as well. run `npm run peg-parse` to update the parser from
>grammer.txt
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/31#issuecomment-227639738

-- 
Mathieu ABOU-AICHI
